name = "counter-linkedin"
main = "build/index.js"
compatibility_date = "2026-03-20"
routes = [
  { pattern = "counterlinkedin.com", custom_domain = true }
]

[build]
command = "./scripts/wrangler-build.sh"

[assets]
directory = "./target/site"

[vars]
