name = "counter-linkedin"
main = "build/index.js"
compatibility_date = "2026-06-29"
upload_source_maps = true
routes = [
  { pattern = "counterlinkedin.com", custom_domain = true }
]

[build]
command = "./scripts/wrangler-build.sh"

[assets]
directory = "./target/site"

[observability]
enabled = true

[vars]
